Spielordnung.md

> __JSpO 11.3 (geltende Fassung)__
> In jeder Mannschaft ist abweichend von Ziffer 11.1 eine Spielerin startberechtigt, die in der laufenden Saison einem anderen Verein angehört.
> __JSpO 11.3 (neue Fassung)__
> In jeder Mannschaft ist abweichend von Ziffer 11.1 eine Spielerin startberechtigt, die in der laufenden Saison einem anderen Verein angehört, sofern dieser dem Gastspiel zustimmt.
> __AB zu 11.3 (neu einzufügen)__
> Die Gastspielgenehmigung gilt als erteilt, falls der abgebende Verein mit keiner eigenen Mannschaft an dieser DVM teilnimmt.
> __JSpO 14.2 (geltende Fassung)__
> In jeder Mannschaft ist abweichend von Ziffer 9.1 eine Spielerin startberechtigt, die in der der DVM vorangegangenen Saison einem anderen Verein angehörte, wenn sie im Qualifikationszyklus zu dieser DVM - …

Gastspielgenehmigung in der DVM U20w und U14w

---

Spielordnung.md

> __JSpO 16.1 (geltende Fassung)__
> An der DVM U10 nehmen Vereinsmannschaften teil. Jede Mannschaft besteht aus vier Jugendlichen der Altersklasse U10. Spielberechtigt sind abweichend zu 9.1 alle Spieler, die in der laufenden Saison für diesen Verein spielberechtigt sind.
> __JSpO 16.1 (neue Fassung)__
> An der DVM U10 nehmen Vereinsmannschaften teil. Jede Mannschaft besteht aus vier Jugendlichen der Altersklasse U10. Teilnahmeberechtigt im Sinne von 1.4 Satz 2 Nr. 3 sind alle Jugendlichen, die in der laufenden Saison für diesen Verein spielberechtigt sind.
Die Deutsche Vereinsmeisterschaft U10 genießt eine besondere Rolle in allen DVM-Turnieren: Sie wird als offenes Turnier mit verkürzter Bedenkzeit ausgetragen und trägt bei alljährlich etwa 50 teilnehmenden Mannschaften einen …

JSpO 16.1: Spielberechtigung DVM U10 durch Vereinsmitgliedschaft

---

Spielordnung.md

> # Antrag des AK Schulschach zur Spielordnung
> der AK Schulschach der DSJ stellt den Antrag §17.3 der Jugendspielordnung wie folgt zu
ändern:
> *(siehe Commit c64d0de)*
> gez. Simon M. Claus

JV 2015: Antrag des AK Schulschach zur DSM-Feldgröße

---

Spielordnung.md

Im Zuge der letzten Änderungen der FIDE-Regeln wurde der ehemalige Artikel 10.2 (Remisantrag in der Endspurtphase) in den Anhang G verschoben. Die Endspurtphase kommt nur in Schnellschachpartien mit fester Grundbedenkzeit zu tragen, also in der DVM U10, die mit einer Bedenkzeit von einer Stunde ausgetragen wird.
Anhang G4 schafft die neue Möglichkeit, dass der Spieler statt den Schiedsrichter um eine Remisentscheidung zu ersuchen die Umstellung auf eine Inkrementbedenkzeit einfordern kann. Die FIDE-Regeln räumen im folgenden Anhang G5 ein, dass diese Regelung im Vorfeld außer Kraft gesetzt werden kann.
Der AKS hat auf seiner Sitzung am 8. Januar 2016 in Düsseldorf entschieden, von dieser Möglichkeit Gebrauch zu machen und die Anwendung von G4 bei der DVM U10 zu unterbinden. Es scheint in …

Anhang G4 in DVM U10 nicht anwenden

---

Spielordnung.md

Im oben genannten Auszug wird auf das Meldeprozedere im Vorfeld von Mannschaftsmeisterschaften eingegangen. Die genannte Ausführungsbestimmung gilt für all unsere Mannschaftsmeisterschaften – Schulschach-, Länder- und Vereinsmeisterschaften. Diese weisen unterschiedliche Mannschaftsgrößen auf: Bei den DVM reisen Mannschaften mit bis zu fünf Jugendlichen (davon ein/e Ersatzspieler/in), bei der DLM mit bis zu zehn Jugendlichen (davon zwei Ersatzspieler/innen). Diese sehr unterschiedliche Mannschaftsgröße spiegelt sich derzeit nicht in der Größe der im Vorfeld zu meldenden Mannschaftskader wider.
Die feste Kadergröße von 15 ließe bei der Meldung zur DLM nur fünf Reservemeldungen zu. Der frühe Meldetermin von i.d.R. vier Wochen im Voraus erlaubt jedoch keine solch verbindliche …

AB 5.7: Abweichende Kadergröße bei Mannschaftsturnieren durch Festlegung in der Ausschreibung

---

Spielordnung.md

> **AB zu 5.9, Absatz 1 (geltende Fassung)**
> Abweichend zu AB zu 2.1 (1) hat der Turnierverantwortliche die Auslosung dahingehend zu beeinflussen, dass die zwei in der Startrangliste am höchsten geführten Mannschaften des gleichen Landesverbands (bei den Ländermeisterschaften) bzw. des gleichen Vereins (bei den Vereinsmeisterschaften) in möglichst früher Runde aufeinander treffen.
> **AB zu 5.9, Absatz 1 (neue Fassung)**
> Reisen 20 oder weniger Mannschaften an, hat der Turnierverantwortliche abweichend zu AB zu 2.1 (1) die Auslosung dahingehend zu beeinflussen, dass die zwei in der Startrangliste am höchsten geführten Mannschaften des gleichen Landesverbands (bei den Ländermeisterschaften) bzw. des gleichen Vereins (bei den Vereinsmeisterschaften) in möglichst früher Runde aufeinander …

Vereins- und Verbandspaarungen bei Mannschaftsturnieren

---

Spielordnung.md

> **AB zu 14.1 (geltende Fassung, zu streichen)**
> Abweichend von Ziffer 2.5 beträgt die Spielzeit 75 Minuten für 40 Züge, danach zusätzliche 15 Minuten für die restlichen Züge, bei zusätzlichen 30 Sekunden pro Zug von Beginn an.
*Commit 5836116*
Die Deutschen Vereinsmeisterschaften werden bislang mit drei verschiedenen Bedenkzeiten ausgetragen: In den Altersklassen U14, U14w, U16, U20 und U20w wird mit der üblichen Bedenkzeit „Fischer kurz“ gespielt, d.h. 90 Minuten für 40 Züge, danach zusätzliche 30 Minuten für die restlichen Züge, bei zusätzlichen 30 Sekunden pro Zug von Beginn an. Dies ist gemäß JSpO 2.5 die Standardbedenkzeit bei Turnieren der DSJ. Die DVM U12 weicht bislang hiervon ab und wird mit insgesamt 30 Minuten geringerer Grundbedenkzeit ausgetragen, d.h. 75 Minuten für 40 …

Streichung AB zu 14.1 (Abweichung von Standardbedenkzeit in der DVM U12)

---

Spielordnung.md

> **JSpO 5.7 (geltende Fassung)**
> Die Mannschaften sind nach Spielstärke aufzustellen. Nach dem Meldeschluss sind keine Nachmeldungen mehr möglich. Die Reihenfolge darf während des Turniers nicht mehr geändert werden. Falsche Brettbesetzung zieht den Partieverlust für die zu tief eingesetzten Spieler nach sich.
> **JSpO 5.7 (neue Fassung, Änderung kursiv)**
> Die Mannschaften sind nach Spielstärke aufzustellen. Nach dem Meldeschluss sind keine Nachmeldungen mehr möglich; *der Turnierverantwortliche kann Ausnahmen zulassen*. Die Reihenfolge darf während des Turniers nicht mehr geändert werden. Falsche Brettbesetzung zieht den Partieverlust für die zu tief eingesetzten Spieler nach sich.
*Commit 44bf5c1*
Bislang läuft das Meldeverfahren für die DVM und DLM so ab, dass sechs bis acht …

JSpO 5.7: Nachmeldungen zu Mannschaftsturnieren in Ausnahmefällen zulassen

---

Spielordnung.md

> **JSpO 1.7, Absatz 2 (geltende Fassung)**
> Die Ausführungsbestimmungen in ihrer aktuellen Fassung werden mit der Spielordnung bei allen Turnieren der DSJ durch Aushang vor Ort veröffentlicht; darüber hinaus werden sie auf den Internetseiten der DSJ veröffentlicht.
> **JSpO 1.7, Absatz 2 (neue Fassung)**
> Die Ausführungsbestimmungen in ihrer aktuellen Fassung werden mit der Spielordnung auf den Internetseiten der DSJ veröffentlicht. Sie sind bei allen Turnieren der DSJ gedruckt vorzuhalten.
*Commit 2c3e4b5*
Die Spielordnung mit ihren Ausführungsbestimmungen füllt gedruckt 20 Seiten. Ein Aushang der Regeln bei DSJ-Turnieren ist weder praktikabel noch hilfreich. In der Praxis hat sich etabliert, eine Mappe mit allen gedruckten Ordnungen bei der Turnierleitung vorzuhalten, die von …

JSpO 1.7, Absatz 2: Bekanntmachung der Spielordnung ohne verpflichtendes Ausdrucken

---

Spielordnung.md

von der Landesschachjugend Sachsen-Anhalt. [Abgedruckt im JV-Heft zur JV 2017 in Gießen.](http://www.deutsche-schachjugend.de/fileadmin/dsj_image/wir/Verband/JV_2017/Antraege-JV-2017.pdf#page=6)
*Commit f3846b2*
Die geänderte Zweitwertung soll bei Mannschafts-Turnieren im Schweizer System die Stärke der Gegner ebenso berücksichtigen wie die erzielten Brettpunkte. Gerade bei DVM weisen die Teilnehmerfelder oft ein großes Gefälle auf. Leichtere Gegner bieten gleichzeitig sehr viel bessere Chancen auf hohe Brettpunkte, so dass Mannschaften mit "leichterer" Auslosung bei der bisherigen Wertung doppelt bevorteilt sind:
- bessere Möglichkeiten, mehr Mannschaftspunkte zu erzielen 
- Vorteile bei der Zweitwertung
Der Begriff "Sonneborn-Berger-Wertung" ist für Mannschaftsturnier von der FIDE …

Sonneborn-Berger als erste Feinwertung bei Mannschaftsturnieren nach Schweizer System

---

Spielordnung.md

> **AB zu 2.1 (geltende Fassung, Auszug)**
> Gemäß Art. 11.3 lit. b der FIDE-Regeln ist es Spielern untersagt, ein Mobiltelefon oder anderes elektronisches Gerät in das Turnierareal mitzubringen. Bei Verstößen sind Strafen nach Ziffer 3.1 auszusprechen.
> **AB zu 2.1 (neue Fassung, Auszug, Änderung hervorgehoben)**
> Gemäß Art. 11.3 lit. b der FIDE-Regeln ist es Spielern untersagt, ein Mobiltelefon oder anderes elektronisches Gerät in das Turnierareal mitzubringen. Bei Verstößen sind Strafen nach Ziffer *3* auszusprechen.
*Commit 0a08d8b*
Der Passus zu 11.3 lit. b der FIDE-Regeln wurde aufgenommen, da dort seit der Änderun-gen 2014 dem Turnierveranstalter die Möglichkeit eingeräumt wird, für Fälle des Mitführens eines Handys oder anderen elektronischen Kommunikationsgeräts mildere …

Verweis auf allgemeinen Sanktionskatalog JSpO 3 für Handybetrug o.ä.

---

Spielordnung.md

> **AB zu 5.7, Absatz 4 (geltende Fassung)**
> 
> Es können in Mannschaftswettkämpfen nur Spieler aufgestellt werden, die vor Ort anwesend sind.
> 
> **AB zu 5.7, Absatz 4 (neue Fassung)**
>
> Bei Meisterschaften, die in einem ununterbrochenen Zeitraum am gleichen Ort stattfinden, können in Mannschaftswettkämpfen nur Spieler aufgestellt werden, die vor Ort anwesend sind.
*Commit 6497af49aa87e9de77c3aea3d7f3f954169de602*
Die JSpO gibt an einigen Stellen explizit Regelungen für Turniere auf, die in einem ununterbrochenen Zeitraum am gleichen Ort stattfinden. Dies ist aktuell bei allen DSJ-Mannschaftsmeisterschaften der Fall, gleichwohl hält sich die Ordnung einen Spielbetrieb ähnlich eines Ligensystems mit mehreren Spielterminen offen.
Die genannte Einschränkung auf nur anwesende Spieler …

AB zu 5.7: Aufstellung anwesender Spieler

---

Spielordnung.md

> **AB zu 2.1 (geltende Fassung, Auszug)**
>
> Gemäß Art. 11.3 lit. b der FIDE-Regeln ist es Spielern untersagt, ein Mobiltelefon oder anderes elektronisches Gerät in das Turnierareal mitzubringen. Bei Verstößen sind Strafen nach Ziffer 3 auszusprechen.
>
> Gemäß Art. 9.1 lit. a der FIDE-Regeln ist es Spielern ohne Zustimmung des Schiedsrichters nicht gestattet, vor Vollendung des 20. Zuges Remis zu vereinbaren. Umgehen die Spieler diese Regelung, kann dies nach Ziffer 3 bestraft werden.
>
> Abweichend von Art. 7.5 lit. b und Anhang A4 lit. b der FIDE-Regeln verliert ein Spieler erst nach dem dritten regelwidrigen Zug die Partie. Art. 7.5 lit. b der FIDE-Regeln ist analog auf den ersten und zweiten regelwidrigen Zug anzuwenden.
> 
> **AB zu 2.1 (neue Fassung, Auszug)**
> 
> Gemäß Art. …

Verweiskorrektur in AB zu 2.1 für FIDE-Regeln ab 01.01.2018

---

Spielordnung.md

> **JSpO 1.5 (geltende Fassung)**
> 
> Der Arbeitskreis Spielbetrieb (AKS) unter Leitung des Nationalen Spielleiters ist zuständig für die Austragung aller von der DSJ ausgeschriebenen Turniere. Die Vorbereitung und Turnierleitung obliegt einer vom Arbeitskreis Spielbetrieb (AKS) bestimmten, fachlich geeigneten Person ("Turnierverantwortlicher"); aus Gründen der Zweckmäßigkeit können die Vorbereitung der Turniere und die Turnierleitung vor Ort auf mehrere Personen verteilt werden. Grundsätzlich wird vom AKS eines seiner Mitglieder bestimmt, das die Vorbereitung eines oder mehrerer Turniere koordiniert.
> 
> **JSpO 1.5 (neue Fassung)**
> 
> Der Arbeitskreis Spielbetrieb (AKS) unter Leitung des Nationalen Spielleiters ist zuständig für die Austragung aller von der DSJ ausgeschriebenen …

JSpO 1.5: Implizite Festlegung des Turnierverantwortlichen

---

Spielordnung.md

> **JSpO 6.5 (geltende Fassung)**
>
> Der Ausrichter erhält in jeder ausgerichteten Altersklasse einen Freiplatz.
> 
> In den Altersklassen U14, U12, U12w, U10 und U10w erhalten alle Kaderspieler in ihrer jeweiligen Altersklasse einen Freiplatz.
> 
> Es können jeweils bis zu zehn weitere Freiplätze vergeben werden. Der AKS kann das Freiplatzkontingent bei außergewöhnlichen Umständen um jeweils bis zu vier weitere Freiplätze erhöhen.
>
> **JSpO 6.5 (neue Fassung)**
>
> In den Altersklassen U14, U12, U12w, U10 und U10w erhalten alle Kaderspieler in ihrer jeweiligen Altersklasse einen Freiplatz.
> 
> Es können jeweils bis zu elf weitere Freiplätze vergeben werden. Der AKS kann das Freiplatzkontingent bei außergewöhnlichen Umständen um jeweils bis zu vier weitere Freiplätze erhöhen.
*Commit …

JSpO 6.5: Kein verpflichtender Freiplatz für DEM-Ausrichter

---

Spielordnung.md

Die Spielberechtigung für Jugendliche des sogenannten „Euregio“-Gebiets entlang der Grenzen zur Bundesrepublik Deutschland ist bereits seit mehreren Jahren für die DVM in JSpO 8.2 geregelt. Nachdem sich die Jugendversammlung im vergangenen Jahr grundsätzlich positiv gegenüber einer Ausweitung auf alle Meisterschaften positioniert hat, beantragt der AKS nun diese Änderung. Zum Zwecke der Übersichtlichkeit sind die hierfür notwendigen Ordnungsänderungen im Antrag (a) zusammengefasst; die sich daraus ergebenden Korrekturen von Referenzen sind im Antrag (b) zusammengefasst. Antrag (a) führt die notwendigen Ordnungsänderungen nicht in ihrer Textreihenfolge auf, sondern in der Form „Streiche den DVM-Teil und füge ihn im allgemeinen Teil ein“. Eine Fassung, wie die Jugendspielordnung nach …

Ausweitung Euregio auf alle DSJ-Meisterschaften

---

Spielordnung.md

> **JSpO 1.5 (neu einzufügen)**
> Teilnahmeberechtigt im Sinne von 1.4 Satz 2 Nr. 3 sind auf begründeten Antrag zusätzlich Jugendliche, die
> 1.	ihren bisherigen Lebensmittelpunkt aufgegeben und nun in der Bundesrepublik Deutschland haben oder
> 2.	in der Vergangenheit bereits teilnahmeberechtigt waren nach 1.4 Satz 2 Nr. 2 und an Turnieren nach 1.3 teilgenommen haben.
> 
> **Die alten Nummern 1.5 bis 1.7 erhöhen sich um 1.**
> 
> **AB zu 1.5 (neu einzufügen)**
> Dem Antrag ist zu entsprechen, falls der Jugendliche einen starken Bezug zum deutschen Schach hat. Die Entscheidung hierüber trifft der Vorstand. Er berücksichtigt bei seiner Entscheidung die Einschätzung des Landesverbands, sofern sie vorliegt.
In der jüngsten Vergangenheit ist es zu zwei Härtefällen gekommen, bei denen …

Einzelfallprüfung zur Teilnahmeberechtigung an Deutschen Meisterschaften

---

Spielordnung.md

Der Arbeitskreis Spielbetrieb strebt die Entwicklung der DVM U10 hin zu einer Meisterschaft mit 40 Qualifikationsplätzen an. Es werden zwei Varianten vorgeschlagen, wie diese verteilt werden könnten: Antrag (a) behandelt die Vergabe der Plätze über Regionalgruppen, Antrag (b) die Vergabe direkt über die Landesverbände. Es handelt sich um konkurrierende Anträge. Die Referenzen zu 1.4, 8.2 und 8.4 beziehen sich auf die Nummerierung nach Genehmigung von Antrag 3 (b) und sind andernfalls entsprechend zu ersetzen.
> **JSpO 15.1 (geltende Fassung)**
> An der DVM U10 nehmen Vereinsmannschaften teil. Jede Mannschaft besteht aus vier Jugendlichen der Altersklasse U10. Teilnahmeberechtigt im Sinne von 1.4 Satz 2 Nr. 4 sind alle Jugendlichen, die in der laufenden Saison für diesen Verein …

DVM U10: Meisterschaft mit Qualifikationsplätzen

---

Spielordnung.md

Die Anträge (a) und (b) werden gemeinsam zur Abstimmung gestellt.
> **JSpO 2.4 (geltende Fassung)**
> Wird eine Meldefrist überschritten, wird schriftlich eine angemessene Nachfrist gesetzt. Bleibt auch die Nachfrist ungenutzt, hat der Turnierverantwortliche in Abstimmung mit dem AKS das Recht, den Platz anderweitig zu vergeben. 
> **JSpO 2.4 (neue Fassung)**
> Wird eine Melde- oder Zahlungsfrist überschritten, wird schriftlich eine angemessene Nachfrist gesetzt. Bleibt auch die Nachfrist ungenutzt, hat der Turnierverantwortliche in Abstimmung mit dem AKS das Recht, den Spieler oder die Mannschaft von der Teilnahme auszuschließen und den Platz anderweitig zu vergeben.
> **§ 5.2 (geltende Fassung)**
> Spieler und Mannschaften können von Veranstaltungen der DSJ ausgeschlossen werden, wenn …

Überschreiten von Melde- und Zahlungsfristen

---

Spielordnung.md

Mit den FIDE-Regeln vom 01.07.2017 haben sich die referenzierten Artikel etwas verschoben.
Anhang A2 wird nun als A.2 geführt, Anhang G wurde durch die Richtlinie in III.4 ersetzt.
In den Neuerungen der FIDE-Regeln vom 01.01.2018 wurden die Schnellschachregeln zudem
dem Turnierschach angeglichen. Den ehemaligen A4 lit. b, der im Schnellschach zum sofortigen
Partieverlust nach einem regelwidrigen Zug führte, gibt es nicht mehr. Stattdessen verliert auch
im Schnellschach erst der zweite regelwidrige Zug, sodass der Verweis in AB zu 16.1 entfernt
werden kann. Dies hat die DSJ außerdem in AB zu 2.1 weiter entschärft, sodass grundsätzlich
erst der dritte regelwidrige Zug die Partie verliert. Da JSpO 2.2 zudem die Abweichung für junge
und unerfahrene Spieler zulässt, ist bei den …

AB zu 16.1 (DSM): Anpassungen an neue FIDE-Regeln

---

Spielordnung.md

> **JSpO 8.2 (geltende Fassung, unverändert)**
> Zur Ermittlung der teilnehmenden Mannschaften werden folgende Regionalgruppen gebildet:
> -    Nord: Berlin, Brandenburg, Bremen, Hamburg, Mecklenburg-Vorpommern, Niedersachsen, Sachsen-Anhalt, Schleswig-Holstein;
> -    West: Nordrhein-Westfalen;
> -    Mitte: Hessen, Thüringen, Rheinland-Pfalz, Saarland;
> -    Süd-Ost: Bayern, Sachsen;
> -    Süd: Baden, Württemberg.
> 
> Die jeweiligen Landesverbände organisieren den zur Ermittlung der Qualifikanten notwendigen Spielbetrieb in eigener Verantwortung.
>
> **AB zu 8.2 (neu einzufügen)**
> Sollte eine Regionalgruppe zur Ermittlung der Qualifikanten einer Altersklasse eine Regionalgruppenmeisterschaft ausspielen, so soll diese Meisterschaft mindestens sechs Plätze bieten.
Zur Bestimmung der …

AB 8.2: Empfehlung zur Gestaltung der Regionalgruppenturniere zur DVM

---

Spielordnung.md

> **JSpO 8.2 (geltende Fassung, unverändert)**
> Zur Ermittlung der teilnehmenden Mannschaften werden folgende Regionalgruppen gebildet:
> -    Nord: Berlin, Brandenburg, Bremen, Hamburg, Mecklenburg-Vorpommern, Niedersachsen, Sachsen-Anhalt, Schleswig-Holstein;
> -    West: Nordrhein-Westfalen;
> -    Mitte: Hessen, Thüringen, Rheinland-Pfalz, Saarland;
> -    Süd-Ost: Bayern, Sachsen;
> -    Süd: Baden, Württemberg.
> 
> Die jeweiligen Landesverbände organisieren den zur Ermittlung der Qualifikanten notwendigen Spielbetrieb in eigener Verantwortung.
>
> **AB zu 8.2 (neu einzufügen)**
> Sofern sich eine Regionalgruppe aus mehreren Landesverbänden zusammensetzt und diese sich nicht auf einen Austragungsmodus zur Ermittlung der Qualifikanten in einer Altersklasse einigen, kann jeder dieser …

AB 8.2: Konfliktbeilegung für die Regionalgruppenturniere zur DVM

---

Spielordnung.md

> **AB zu 15.1 (geltende Fassung)**
> Abweichend von Ziffer 2.5 beträgt die Spielzeit 60 Minuten. Anhang III.4 der FIDE-Regeln findet keine
Anwendung.
> **AB zu 15.1 (neue Fassung)**
> Abweichend von Ziffer 2.5 beträgt die Spielzeit 60 Minuten. Es findet Anhang III der FIDE-Regeln ohne
III.4 Anwendung.
Gemäß der aktuellen FIDE-Regeln findet Anhang III zur Endspurtphase nur in Turnieren Anwen-
dung, für die dies im Voraus angekündigt wurde. Um dies zu verdeutlichen, wird der Wortlaut in
AB zu 15.1 entsprechend angepasst.

Klarstellung zur Anwendung von Anhang III bei der DVM U10

---

Spielordnung.md

> **AB zu 15.1 (zu ergänzen)**
> Abweichend zu AB zu 2.5 (1) erhält jeder Spieler, der nach der Erklärung des Schiedsrichters, die Runde sei eröffnet (Spielbeginn), im Spielbereich eintrifft, eine Zeitstrafe von 15 Minuten, vorausgesetzt dass dies nicht seine erste Verspätung in diesem Turnier war.
Die Ausführungsbestimmungen zu 2.5 sehen vor, dass Spieler, die sich erstmalig zur Partie verspäten, eine Zeitstrafe von 15 Minuten erhalten, und bei jedem weiteren Zuspätkommen in diesem Turnier ihre Partie verlieren. Wenngleich solche Verspätungen in der DVM U10 sehr selten sind, ist die bislang anzuwendende Zeitstrafe in Anbetracht der Gesamtbedenkzeit von einer Stunde unverhältnismäßig. Zur DVM U10 scheint es ausreichend, erst ab dem zweiten Vergehen vom Bedenkzeitabzug Gebrauch zu machen, …

Karenzzeitregelung bei der DVM U10

---

Spielordnung.md

> **AB zu 2.1 [Spielweise, Spielregeln, Streitfälle] (Auszug, geltende Fassung, zu streichen)**
> Abweichend von Art. 7.5.5 der FIDE-Regeln verliert ein Spieler erst nach dem dritten regelwidrigen Zug
die Partie. Art. 7.5.5 der FIDE-Regeln ist analog auf den ersten und zweiten regelwidrigen Zug anzu-
wenden.
> **AB zu 15.1 [DVM U10] (neu zu ergänzen)**
> Abweichend von Art. 7.5.5 der FIDE-Regeln verliert ein Spieler erst nach dem dritten regelwidrigen Zug
die Partie. Art. 7.5.5 der FIDE-Regeln ist analog auf den ersten und zweiten regelwidrigen Zug anzu-
wenden.
Gemäß der aktuellen FIDE-Regeln verliert bereits der zweite regelwidrige Zug die Partie. Die gel-
tende Fassung in AB zu 2.1 ist nicht in Einklang zu bringen mit der gleichermaßen gewünschten
Elo-Auswertung der deutschen …

Verschieben von AB bzgl. Ahndung regelwidriger Züge von 2.1 nach 15.1

---

Spielordnung.md

*Die Schachjugend Berlin hat zur Jugendversammlung 2018 in Göttingen Anträge zur Reduzierung der Runden mit einer Erhöhung der Bedenkzeit für die Altersklassen U10 und U12 der Deutschen Einzelmeisterschaft (DEM) gestellt. Sie hat diese Änderung in vier Anträge aufgeteilt, deren Antragstext und Begründung sich im [Berichtsheft zur Jugendversammlung](https://www.deutsche-schachjugend.de/fileadmin/dsj_image/wir/Verband/JV_2018/AntraegeJugendversammlung.pdf) auf den Seiten 65 bis 68 findet.*
*Der Einfachheit halber wurden nur die beiden beschlossenen Änderungen als Commit 459ad2cc4b426c43afbb6510436e524a348ee5a6 auf GitHub abgebildet.*

DEM U12/U12w: Verkürzung auf 9 Runden, Bedenkzeitverlängerung auf Fischer kurz

---

Spielordnung.md

> **AB zu JSpO 8.3 (geltende Fassung, Auszug)**
> Der Ausrichter kann mit einer zweiten Mannschaft starten, sofern eine Mannschaft des ausrichtenden Vereins bereits qualifiziert ist und dies zum Erreichen einer geraden Teilnehmerzahl führt.
> **AB zu JSpO 8.3 (neue Fassung, Auszug)**
> Der Ausrichter kann mit einer zweiten Mannschaft starten, sofern dies zum Erreichen einer geraden Teilnehmerzahl führt.
Sagt eine Mannschaft zur DVM nach Meldeschluss ab, wird zuerst ein Nachfolger innerhalb der gleichen Regionalgruppe gesucht und ggf. anschließend der noch freie Platz bundesweit ausgeschrieben. Je nach Zeitpunkt der Absage ist dieses Verfahren jedoch zu langwierig und damit nicht geeignet, das Teilnehmerfeld kurzfristig gerade werden zu lassen. In diesen Fällen sollte dem Ausrichter die …

AB zu 8.3: Zweitmannschaften als Gerademacher zur DVM zulassen

---

Spielordnung.md

> **AB zu JSpO 15.1 (geltende Fassung, Auszug)**
> Abweichend von Ziffer 2.5 beträgt die Spielzeit 60 Minuten. Es findet Anhang III der FIDE-Regeln ohne III.4 Anwendung.
> **AB zu JSpO 15.1 (neue Fassung, Auszug)**
> Abweichend von Ziffer 2.5 beträgt die Spielzeit 55 Minuten bei zusätzlichen 5 Sekunden pro Zug von Beginn an.
Die DVM U10 ist – mit Ausnahme der Deutschen Schulschachmeisterschaften – die einzige Meisterschaft, die ohne Inkrement ausgespielt wird. Mit der Änderung auf einen Modus mit Inkrement soll verhindert werden, dass eine Partie nicht „schachlich“ beendet werden kann. Eine technisch gewonnene Stellung soll nicht aufgrund mangelnder Zeit Remis oder verloren gegeben werden müssen. Aus diesem Grund wird ein Inkrement von 5 Sekunden pro Zug eingeführt. Zwar war es mit der …

AB zu 15.1: Bedenkzeit DVM U10 auf Inkrement umstellen

---

Spielordnung.md

> **JSpO 7.1 (geltende Fassung)**
> An der DLM nehmen Landesverbandsmannschaften teil. Jeder Landesverband kann mindestens eine Mannschaft stellen. Der Ausrichter darf eine weitere Landesauswahl melden.
> **Ergänzung zu JSpO 7.1 für die DLM 2020**
> Der AKS wird ermächtigt, im Jahr 2020 bis zu 11 Mannschaften aus dem Ausland zur DLM zuzulassen. Die Mannschaften sollen Nationen oder Regionen (vergleichbar den Bundesländern) repräsentieren. Der AKS wird ermächtigt, insoweit von der Spielordnung abzuweichen und mit der Ausschreibung die Teilnahmemodalitäten festzulegen.
> Es wird nur eine Mannschaft pro Landesverband zugelassen. Zur Vermeidung einer ungeraden Teilnehmerzahl kann nach Ablauf der Meldefrist eine Zweitmannschaft eines Landesverbandes zugelassen werden.
> Teilnahmeberechtigt im …

Teilnahme von internationalen Mannschaften an der DLM 2020

---

Spielordnung.md

> **JSpO 13.2 (neu einzufügen)**
> Ziffer 8.4 findet keine Anwendung. 
> **Die nachfolgenden Punkte verschieben sich entsprechend.**
Im Allgemeinen ist bei den DVM je Altersklasse nur eine Mannschaft pro Verein startberechtigt. Für die offene DVM U20w ist diese Beschränkung bereits seit einiger Zeit aufgehoben. Auch für die DVM U14w soll es künftig Vereinen ermöglicht werden, sich mit mehreren Mannschaften zur Teilnahme zu qualifizieren. In diesem Fall werden die entsprechenden Mannschaften gemäß AB zu JSpO 5.9 in möglichst früher Runde gegeneinander gepaart.

Zulassen von Zweitmannschaften zur DVM U14w

---

Spielordnung.md

> **JSpO 8.3 (geltende Fassung)**
> Der Ausrichter erhält einen Freiplatz. Die übrigen Teilnehmerplätze werden zu gleichen Teilen nach Qualität (Erfolge der vergangenen drei Jahre) und Quantität auf die Regionalgruppen verteilt. Das Nähere regeln die Ausführungsbestimmungen.
> **JSpO 8.3 (neue Fassung)**
> Der Ausrichter erhält einen Freiplatz, es können bis zu zwei weitere Freiplätze vergeben werden. Die übrigen Teilnehmerplätze werden zu gleichen Teilen nach Qualität (Erfolge der vergangenen drei Jahre) und Quantität auf die Regionalgruppen verteilt. Das Nähere regeln die Ausführungsbestimmungen. 
> **AB zu JSpO 8.3 (Auszug, zu ergänzen)**
> Die Freiplätze vergibt der Spielausschuss.
> **JSpO 15.4 (geltende Fassung)**
> Abweichend zu 8.2 und 8.3 ergibt sich das Teilnehmerfeld wie folgt: …

Freiplätze zur DVM

---

Spielordnung.md

Auf dem Agendatreffen Schulschach (siehe Vorstandsbericht) wurde intensiv die Thematik angesprochen, dass die Deutschen Schulschachmeisterschaften in den älteren Wettkampfklassen sehr stark von Vereinsmannschaften und Vereinsspielern dominiert werden, was viele reine Schulmannschaften abschreckt und dazu führt, dass sich diese nicht mehr beteiligen. Diesem Fakt soll dadurch entgegengewirkt werden, dass die Mannschaftsgröße von vier auf sechs Spielende erhöht werden soll. Das Agendatreffen sieht dieses sogar als einen Einstieg in eine eventuell spätere erfolgende weitere Vergrößerung der Mannschaftstärke. Zuerst ist aber die Auswirkung der Erhöhung um zwei Spielende auszuwerten. Zudem wird immer wieder die Wiedereinführung der WK I ins Gespräch gebracht. Aus den bekannten …

Antrag Spielberechtigung + Mannschaftsgröße WK II

---

Spielordnung.md

Der Arbeitskreis Spielbetrieb präzisiert mit dieser Änderung der Ausführungsbestimmungen die Rechte des Mannschaftsführers und schränkt diese Rolle auf in der aktuellen Runde eingesetzte Spieler ein, es folgt eine Kurzbegründung:
Ein spielstarker Mannschaftsführer bringt offensichtliche sportliche Vorteile. Des weiteren bringt der Wechsel der Mannschaftsführerrolle unter Mitreisenden, Trainern etc. eine für die Anzahl der Schiedsrichter nicht überprüfbare Menge an Personen, die potentiell über elektronische Geräte verfügen, da im Gegensatz z.B. zur Schacholympiade nicht ein Schiedsrichter pro Mannschaftskampf gestellt werden kann.
Weitere Fragen beantworten die Nationalen Spielleiter gerne unter spielbetrieb@deutsche-schachjugend.de oder direkt als Kommentar.

Anpassungen AB Mannschaftsführer

---

Spielordnung.md

Im Zuge der Vorbereitung zur diesjährigen U10 Meisterschaft haben die Schach- freunde des Hamburger Schachjugendbundes korrekterweise darauf hingewiesen, dass die Sonderregelung zur Spielberechtigung für die DVM U10 unklar formuliert ist.
Im Antrag von 2015 zur Öffnung der Teilnahmeberechtigung für die DVM U10 unab- hängig von der Staatsbürgerschaft oder dem Lebensmittelpunkt wurde versäumt, die vorherige explizite Ausnahmeregelung zur Spielberechtigung beizubehalten. Dies soll durch diesen Einschub korrigiert werden.
Die Historie ist einsehbar im Github Repository der Schachjugend: https://github.com/Schachjugend/Spielordnung/pull/18.
Dieser Korrekturantrag dient somit lediglich der Klarstellung der bisherigen aufgrund der Ordnungshistorie angewandten Praxis.

Korrektur Sonderregelungen DVM U10

---

Spielordnung.md

Begründung: Das Spielen mit Inkrement ist dank digitaler Uhren inzwischen den meisten Spielern geläufiger und weit verbreitet. Auch die Deutschen Jugendeinzel-, Vereins- und Ländermeisterschaften werden mit Inkrement gespielt. Die Gründe dafür liegen auf der Hand: Es gewinnt der Spieler mit der besseren Stellung und nicht derjenige, der es schafft den Gegner trotz weniger Materials oder schlechterer Stellung noch über die Zeit zu ziehen. Auch werden v.a. die Schiedsrichter entlastet, da es bei Zeitnotschlachten nicht mehr zu Anträgen nach Richtlinie III kommen kann. Für Spannung ist weiterhin gesorgt, allerdings werden Partien nun eher auf dem Brett entschieden, weniger mit der Uhr und nicht mehr durch die Schachregeln.
Da erscheint es sinnvoll, dass auch die DSSM der älteren …

Bedenkzeit Schulschach - Antrag der Schachjugend in Berlin JHV 2020

---

Spielordnung.md

Der Arbeitskreis Spielbetrieb hat sich schon länger mit der Thematik der weiblichen DVMs beschäftigt. Zunächst war es eher die U20w, die weniger teilnehmende Teams hatte und in den letzten Jahren die U14w. Im Zuge der DVM 2019 haben wir die teilnehmenden Verein der weiblichen Altersklassen befragt, wie sie zu einer Umstrukturierung der weiblichen Meisterschaften stehen und haben überwiegend positive Rückmeldungen zu den beantragten Änderungen erhalten.
Bei einer Analyse der Turniere sowie der Mitgliederzahlen sind wir zu folgenden Erebnissen gekommen:
Die aktuelle Anzahl an Mädchen/Frauen nimmt mit dem Alter stetig ab. Während es in der Gruppe unter 12 Jahren noch über 2000 Mädchen gibt, sieht man wie in den Folgejahren die Jahrgänge mehr abnehmen.
In der U14w spielen bereits jetzt schon …

Einführung DVM U16w und U12w - Streichung DVM U14w

---

Spielordnung.md

Begründung: 
Der Antrag zur Einführung einer Deutschen Meisterschaft U8 im Jahr 2022 wurde auf der Jugendversammlung im März 2020 in Freiburg mit 132 Ja-Stimmen und 118 Nein-Stimmen mehrheitlich angenommen. Daraufhin hat der Arbeitskreis Spielbetrieb in Kooperation mit Olaf Sill (BER), Viktoria Hauk (HES), Birger Pommerenke (SHO) und Verena Wunderlich (NRW) ein Konzept zur Einführung der Meisterschaft erarbeitet. Um das Konzept umsetzen zu können, sind die oben aufgelisteten Ordnungsänderungen notwendig.

JV 2021: Einführung einer Deutschen Meisterschaft U8/w

---

Spielordnung.md

Begründung: 
Die Jahresdurchschnittspunkte basieren auf der Annahme, dass sich die Rundenzahl der DEM nicht ändert. Doch dann sorgte die Corona-Pandemie für Abweichungen. Deswegen soll zukünftig der Punktedurchschnitt anstatt der Punktesumme in die Durchschnittsbildung einfließen.
Warum werden die Durchschnittspunkte mit zehn multipliziert?
Altes System: Bei einem neunrundigen Turnier werden durchschnittlich 4,5 Punkte erzielt. Bei einem elfrundigen Turnier werden durchschnittlich 5,5 Punkte erzielt.
Neues System: Unabhängig von der Rundenzahl werden durchschnittlich 50 % der
Punkte (= 0,5) erzielt. Durch die Multiplikation mit zehn ergeben sich im Durchschnitt 5 Punkte, so dass sich das Verhältnis von Durchschnitts- und Bonuspunkten nur geringfügig verschiebt.
Gemäß aktuellem Verfahren …

JV 2021: Berechnung der DEM-Kontingente

---

Spielordnung.md

Begründung: 
Die rechtliche Verselbstständigung der Deutschen Schachjugend als eingetragener Verein führt dazu, dass die Spielordnung daraufhin anzupassen ist.
1.1. knüpft nun klarstellend an den Spielbetrieb der Landesschachjugenden an. Damit
werden auch rechtlich selbstständige Landesschachjugenden, die nicht Mitglied des
DSB sind, ausdrücklich eingeschlossen.
1.2. enthält nun eine verständlichere Altersklassen-Definition, die auch § 29 Abs. 2 der
DSJ-Satzung aufstellt. Eine inhaltliche Änderung erfolgt nicht.
1.7. passt die Zuständigkeiten der Schiedsgerichte an die Vorgaben des § 20 der Satzung und der Recht- und Verfahrensordnung an.
2.1. nennt nun die Satzung der DSJ statt der DSB-Satzung und der ehemaligen DSJ-
Jugendordnung als maßgebliches Regelungswerk.

JV 2021: Anpassung Spielordnung durch Vereinsgründung

---

Spielordnung.md

Begründung: 
Durch 6.1 werden Anforderungen an die Teilnehmerfelder gestellt, die sich nicht immer erfüllen lassen. Gibt es in einer Altersklasse mehrere Kaderspieler, so reduziert sich die Anzahl der möglichen Freiplätze. Zukünftig sollen die Kaderspieler und die Nominierten des DBSB keinen Einfluss auf die Freiplatzvergabe haben.
Die Reduktion der Freiplatzanzahl von „bis zu elf“ auf „bis zu acht“ ist keine echte
Verknappung. Die Maximalanzahl von derzeit elf ist ohnehin theoretischer Natur, da
sie nicht mit der maximalen Feldgröße in Einklang zu bringen ist.
Wir halten es für gerecht, dass auch in den Altersklassen U18, U18w, U16, U16w und
U14w die Kaderzugehörigkeit automatisch zu einer Teilnahmeberechtigung bei der
DEM führt. Es ist sehr ungewöhnlich, dem DSJ-Vorstand die …

JV 2021: Flexibilisierung der DEM-Feldgröße

---

Spielordnung.md

Begründung:
Mehrere deutsche EInzelmeisterschaften zur gleichen Zeit (2.1 AB, 2.8)
Die Regelung sollte sich in der Ordnung und nicht in den AB befinden. Wie die DEM und die DVM 2020 gezeigt haben, kann es zudem dazu kommen, dass unterschiedliche Altersklassen einer DEM bzw. DVM zu verschiedenen Zeiten ausgetragen werden. Auch in diesem Fall soll ein Spieler nur für eines der Turniere startberechtigt sein.
Bedenkzeiten: Die Bedenkzeiten sollten sich, wie in 2.5, in der Ordnung und nicht in den Ausführungsbestimmungen befinden.
DLM 2020: Der 2019 angenommene Antrag sah nicht vor, die die DLM 2020 betreffenden Regelungen zu gegebenem Zeitpunkt wieder zu entfernen.
Korrektur von Verweisen: Der 2020 angenommene Antrag zur DVM sah nicht vor, entsprechend notwendige Anpassungen von Verweisen …

JV 2021: Redaktionelle Anpassungen
